---
baseline: 1.1
total: 5000
days:
  - date: '10-02-2023'
    count: 1
  - date: '12-02-2023'
    count: 2
  - date: '14-02-2023'
    count: 3
  - date: '15-02-2023'
    count: 4
  - date: '18-02-2023'
    count: 5
  - date: '28-02-2023'
    count: 6
