version: "3.7"
services:
  cli:
    image: golang:1.22
    command: go run . calendar config --log DEBUG --out
    working_dir: /app
    environment:
      GOMODCACHE: /app/.pkg
      GOCACHE: /app/.cache
    volumes:
      - .:/app

  service:
    image: golang:1.22
    command: go run . calendar server
    #command: ["/go/bin/dlv", "debug", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient"]
    #env_file: .env
    working_dir: /app
    environment:
      GOMODCACHE: /app/.pkg
      GOCACHE: /app/.cache
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  server_run:
    build:
      context: .
    #command: ["/go/bin/dlv", "debug", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient"]
    #env_file: .env
    ports:
      - "8081:8080"