# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: change Directory
      run: cd cli
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: cd cli && go install github.com/jstemmer/go-junit-report/v2@latest && go build -v ./...
    - name: Test
      run: cd cli && go test -v ./... -json 2>&1 | go-junit-report -parser gojson > testResults.xml

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results
        path: cli/testResults.xml

    - uses: dorny/test-reporter@v1.8.0
      if: success() || failure()    # run this step even if previous step failed
      name: Upload Report
      with:
        artifact: Go-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results